### ISSUE TITLE
"Unknown exception" causing runelite to freeze on startup

### ISSUE THREAD

**Issue by Atrolantra** [Belieal/flipping-utilities#110]
When I booted up RL today, everything was fine with logging in up until after I had typed my password and gone to the welcome splash screen (with the red "click here to play" button). At this point, my RL client froze up. The splash screen animations were choppy and dropped in framerate, clicks on buttons in the splash screen weren't responding and task manager showed RL eating up a massive amount of CPU. This never remedies itself and, if left alone, would eventually grey out as unresponsive with a Windows prompt to close or wait.

The logs appear to indicate that the problem was caused by this plugin. I was able to fix my client by closing it in task manager, opening it again, and disabling this plugin from the runelite settings **before** typing my password and logging in.

Logs attached below, let me know if you'd like more info. Keep up the great work, love the plugin. <3

```
2020-09-19 23:02:16 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.26.1 (launcher version 2.1.3) starting up, args: none
2020-09-19 23:02:18 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-09-19 23:02:18 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-09-19 23:02:18 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 716162773.246
2020-09-19 23:02:20 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-09-19 23:02:20 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-09-19 23:02:20 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "osrs-wiki-crowdsourcing" version "1.0-SNAPSHOT" commit "c808ceccee96008d438ec80d43a6dc36d646437e"
2020-09-19 23:02:20 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.6.2" commit "3e443d7ec7eb8317531f4c7fa700aed592d9c292"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "the-gauntlet" version "1.0-SNAPSHOT" commit "4e13d3ebdf7da91f96c3a47856b2ac19de1e48c8"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.2.0" commit "c6d543b0f9ced23c13fdf44162607df4f1d916a6"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "flipping-utilities" version "1.4.0" commit "02837a0e71dab2752a4a86f7cf29b62533d1727e"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "gauntlet" version "1.0.0" commit "e928b24970bd234aad16c3ec3d9005735b852c08"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zom-leftclick-dropper" version "1.4" commit "d0ea0a406e6e2a06f6bb7e70a6c0d953854c7154"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "door-kicker" version "1.0" commit "04dfc0e0974b28080599bb1ffdc3f7195df922d6"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" version "1.7.2" commit "33beadddd7261b633379ac9d8f214d6ea2f6f65c"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "menu-swapper-extended" version "1.5" commit "4483a14bc657b420f3ddab305b86602b751ad544"
2020-09-19 23:02:21 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-09-19 23:02:23 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 7293ms. Uptime: 9893ms
2020-09-19 23:02:23 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,2560x1400,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,2560x1400,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@484df1a8,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-09-19 23:02:24 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Eric.
2020-09-19 23:02:25 [Client] INFO  com.flippingutilities.FlippingPlugin - initiating load on startup
2020-09-19 23:02:25 [Client] INFO  com.flippingutilities.TradePersister - flipping directory already exists so it's not being created
2020-09-19 23:02:25 [Client] INFO  com.flippingutilities.TradePersister - loading data for Atrolantra
2020-09-19 23:02:25 [Client] INFO  com.flippingutilities.FlippingPlugin - successfully loaded trades
2020-09-19 23:02:25 [Client] INFO  com.flippingutilities.FlippingPlugin - changing view to Accountwide
2020-09-19 23:02:26 [pool-7-thread-1] INFO  com.flippingutilities.CacheUpdater - monitoring directory for changes!
2020-09-19 23:02:28 [pool-3-thread-1] INFO  com.flippingutilities.FlippingPlugin - unknown exception in repeating tasks, error = {}
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.flippingutilities.ui.statistics.StatsPanel.updateTimeDisplay(StatsPanel.java:729)
	at com.flippingutilities.FlippingPlugin.lambda$setupRepeatingTasks$6(FlippingPlugin.java:436)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-09-19 23:02:28 [pool-3-thread-1] INFO  com.flippingutilities.FlippingPlugin - cancelling task and starting it again after 5000 ms delay
2020-09-19 23:02:48 [AWT-EventQueue-0] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.flippingutilities.FlippingPlugin.onConfigChanged(FlippingPlugin.java:1083)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:429)
	at net.runelite.client.plugins.config.ConfigPanel.changeConfiguration(ConfigPanel.java:600)
	at net.runelite.client.plugins.config.ConfigPanel.lambda$rebuild$5(ConfigPanel.java:341)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:126)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2020-09-19 23:02:59 [Client] INFO  com.flippingutilities.FlippingPlugin - Atrolantra has just logged in!
2020-09-19 23:02:59 [Client] INFO  com.flippingutilities.FlippingPlugin - changing view to Atrolantra
2020-09-19 23:03:02 [pool-3-thread-1] INFO  com.flippingutilities.FlippingPlugin - unknown exception in repeating tasks, error = {}
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.flippingutilities.ui.statistics.StatsPanel.updateTimeDisplay(StatsPanel.java:729)
	at com.flippingutilities.FlippingPlugin.lambda$setupRepeatingTasks$6(FlippingPlugin.java:436)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-09-19 23:03:02 [pool-3-thread-1] INFO  com.flippingutilities.FlippingPlugin - cancelling task and starting it again after 5000 ms delay
2020-09-19 23:03:15 [pool-3-thread-1] INFO  com.flippingutilities.FlippingPlugin - unknown exception in repeating tasks, error = {}
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.flippingutilities.ui.statistics.StatsPanel.updateTimeDisplay(StatsPanel.java:729)
	at com.flippingutilities.FlippingPlugin.lambda$setupRepeatingTasks$6(FlippingPlugin.java:436)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-09-19 23:03:15 [pool-3-thread-1] INFO  com.flippingutilities.FlippingPlugin - cancelling task and starting it again after 5000 ms delay
2020-09-19 23:03:22 [D3D Screen Updater] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/sun.java2d.d3d.D3DScreenUpdateManager.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-09-19 23:03:22 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.beans.PropertyChangeSupport$PropertyChangeListenerMap.newArray(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport$PropertyChangeListenerMap.newArray(Unknown Source)
	at java.desktop/java.beans.ChangeListenerMap.add(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.addPropertyChangeListener(Unknown Source)
	at java.desktop/java.awt.Component.addPropertyChangeListener(Unknown Source)
	at java.desktop/java.awt.Container.addPropertyChangeListener(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.installListeners(Unknown Source)
	at org.pushingpixels.substance.internal.ui.SubstanceLabelUI.installListeners(SubstanceLabelUI.java:87)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JLabel.setUI(Unknown Source)
	at java.desktop/javax.swing.JLabel.updateUI(Unknown Source)
	at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
	at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
	at com.flippingutilities.ui.statistics.OfferPanel.<init>(OfferPanel.java:28)
	at com.flippingutilities.ui.statistics.StatItemPanel$$Lambda$1488/0x000000010098a440.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.flippingutilities.ui.statistics.StatItemPanel.<init>(StatItemPanel.java:141)
	at com.flippingutilities.ui.statistics.StatsPanel.lambda$rebuild$3(StatsPanel.java:497)
	at com.flippingutilities.ui.statistics.StatsPanel$$Lambda$1482/0x000000010098bc40.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
```

**Comment by zumaad** [comment]
Hi thanks a ton for the description, I've gotten a couple of messages with people facing similar problems. I'm trying to get to the bottom of this, could you contact me on discord at gaymersriseup#4026 so we can dig deeper. Thanks!

**Comment by zumaad** [comment]
Should be fixed with latest update introducing pagination
