### ISSUE TITLE
Crashes runelite after world hop

### ISSUE THREAD

**Issue by Xortrox** [Belieal/flipping-utilities#147]
Seems to crash when it can't get the

```java
String offerText = client.getWidget(WidgetInfo.GRAND_EXCHANGE_OFFER_CONTAINER).getChild(GE_OFFER_INIT_STATE_CHILD_ID).getText();
```

On line 1387.

2021-03-18 21:51:35 [Client] INFO  c.f.controller.FlippingPlugin - Xortrox has just logged in!
2021-03-18 21:51:35 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2021-03-18 22:36:22 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at com.flippingutilities.controller.FlippingPlugin.lambda$onVarClientIntChanged$37(FlippingPlugin.java:1387)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:79)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at client.at(client.java:38291)
	at client.ak(client.java)
	at bt.qm(bt.java:404)
	at bt.run(bt.java:358)
	at java.lang.Thread.run(Thread.java:748)
	
Or at least my client froze, and this was the only issue I found in the log.

**Comment by zumaad** [comment]
hmm, very interesting. Thanks for the log output! I'll add a guard against a NPE in there. But, it doesn't quite make sense. Is this a recurring problem? Or did this only happen once? 

Cause that code should only be run if the GRAND_EXCHANGE_OFFER_CONTAINER widget is not null and that widget should always have the GE_OFFER_INIT_STATE_CHILD_ID, as every offer setup screen has that child (the child is just the text that says whether its a buy or sell offer).

Do you remember if it happened when you tried world hopping when in the offer setup screen?

**Comment by Xortrox** [comment]
I think perhaps it happened as a result of a different crash issue I've been experiencing. Sometimes my scene is half-rendered and one out of several clients freeze. Perhaps this instead produced the missing container which produced the error. Although it started happening (perhaps coincidentally) after I started using this plugin, and doesn't SEEM to happen without it :S

As for the actual freeze itself it generally gives no errors in the client log when it happens.

**Comment by zumaad** [comment]
Dang, I wish there was an error in the logs or something :( I'll add the NPE guard, but it seems like the problem will still persist. If you don't mind, I'll contact you on discord to troubleshoot further.
