### ISSUE TITLE
ConcurrentModificationException when buying something.

### ISSUE THREAD

**Issue by BramManuel** [Belieal/flipping-utilities#67]
When a successful trade is made, i get the following exception:
```
2020-05-18 21:18:36 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at com.flippingutilities.ui.flipping.FlippingPanel.initializeFlippingPanel(FlippingPanel.java:239)
	at com.flippingutilities.ui.flipping.FlippingPanel.lambda$rebuild$4(FlippingPanel.java:289)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
I am using, the appimage on ubuntu 20.04.

**Comment by Belieal** [comment]
Hi there! Thanks for the bug report.

We believe this is due to the fact that we don't clone the tradeList we use to rebuild the flipping panel. We plan to have this fixed in v1.3.1. :)
